// Static provenance is available from both ordinary Info and watch Info.
import {writeFile} from 'node:fs/promises';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function writeFrequencyCredits(summary,gaps,headways){
  const sections=summary.map(f=>{
    const s=f.source;
    return `<section><h2>${escape(f.name)}</h2><p>${escape(s.attribution)} <a href="${escape(s.terms_url)}">${escape(s.license)}</a>. Derived geometry and frequency data: <a href="frequency/${escape(f.id)}.json.gz">download</a>.</p><p>${f.mappedRoutes} mapped routes; ${f.routesWithProfiles} with available profiles at assembly. Service date ${escape(s.service_date)} (${escape(s.day_type)}); feed ${escape(s.feed_info.feed_version||'version unspecified')}, valid ${escape(s.feed_info.feed_start_date||'calendar')}–${escape(s.feed_info.feed_end_date||'calendar')}; retrieved ${escape(s.retrieved)}.</p><p>${escape(s.note)} ${escape(s.count_anchor)}. Supplied shapes are path geometry, not an identification of individual physical tracks.</p><p>Source ZIP SHA-256: <code>${escape(s.sha256)}</code>. <a href="${escape(s.url)}">Original feed</a>.</p></section>`;
  });
  const m=headways.source;
  const text=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Service frequency sources · Railway Atlas</title><link rel="icon" href="atlas-icon-192.png?rev=1b3a87900a12" type="image/png" sizes="192x192"><link rel="icon" href="atlas-icon.svg?rev=69d552ce10e7" type="image/svg+xml" sizes="any"><link rel="apple-touch-icon" href="atlas-icon-touch-180.png?rev=3d88aa125da7" sizes="180x180"><meta name="application-name" content="Railway Atlas"><style>body{font:16px/1.5 system-ui;max-width:52rem;margin:auto;padding:1rem;color:#172a35;background:#fafafa}code{overflow-wrap:anywhere}a{color:#005785}section{border-top:1px solid #ccd4d8;margin-top:1.5rem}table{border-collapse:collapse}td,th{padding:.5rem;text-align:left;border-bottom:1px solid #ccd4d8}</style><a href="index.html">Railway Atlas</a><h1>Service frequency sources</h1><p>Coverage is partial. The same AM peak, PM peak and off-peak width scale is used worldwide. These are dated weekday schedule/reference profiles, not live departures or a guarantee of service. Unknown and expired profiles are subdued; zero is retained separately. Where directions differ, width uses the lower available directional rate. Listed GTFS windows are configured in each agency's local timezone, not claimed operator peak definitions. Profiles expire at the earlier of feed validity and the 30-day source review interval.</p>${sections.join('')}<section><h2>${escape(m.name)}</h2><p><a href="${escape(m.url)}">Published average headways</a>, checked ${escape(m.checked)}. Seventeen audited whole-route profiles on OSM geometry. Estimates from headway ranges; operator AM/PM/non-peak categories have no invented clock windows. Section-specific rows remain unmatched.</p></section><section><h2>Coverage gaps</h2><table><thead><tr><th>Region</th><th>Status</th><th>Reason</th></tr></thead><tbody>${gaps.map(g=>`<tr><td>${escape(g.region)}</td><td>${escape(g.status)}</td><td>${escape(g.reason)}</td></tr>`).join('')}</tbody></table></section></html>\n`;
  await writeFile('styles/frequency-credits.html',text);
}
